name: My Workflow
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - run: ls -la
      - uses: actions/checkout@v3
      - run: ls -la
      - run: cat .github/workflows/checkout.yml
