name: My Workflow
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - run: ls -la
      - uses: actions/checkout@v4
        with:
          repository: actions/checkout
          ref: v4
      - run: ls -la
